name: agri
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.0
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.3.0
  razorpay_flutter: ^1.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/electrical.png
    - assets/Home.png
    - assets/painting.png
    - assets/plumbing.png

